apiVersion: apps/v1
kind: Deployment
metadata:
  name: mern-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mern-client
  template:
    metadata:
      labels:
        app: mern-client
    spec:
      containers:
      - name: mern-client
        image: mern-client:latest  # Use the image name from your Docker build
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: mern-client
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30000
  selector:
    app: mern-client
