apiVersion: apps/v1
kind: Deployment
metadata:
  name: mern-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mern-server
  template:
    metadata:
      labels:
        app: mern-server
    spec:
      containers:
      - name: mern-server
        image: mern-server:latest  # Use the image name from your Docker build
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: mern-server
spec:
  type: NodePort
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 30001
  selector:
    app: mern-server
